Repository graphql-devise/graphql_devise, pull requests merged in 2020-06, with the labels that each got.

#96 Mount auth operations in main GQL schema
  .gitignore
  README.md
  app/controllers/graphql_devise/application_controller.rb
  app/controllers/graphql_devise/concerns/set_user_by_token.rb
  app/controllers/graphql_devise/graphql_controller.rb
  app/helpers/graphql_devise/mailer_helper.rb
  config/routes.rb
  lib/generators/graphql_devise/install_generator.rb
  lib/graphql_devise.rb
  lib/graphql_devise/mount_method/operation_preparer.rb
  lib/graphql_devise/mount_method/operation_preparers/resource_name_setter.rb
  lib/graphql_devise/mutations/sign_up.rb
  lib/graphql_devise/rails/routes.rb
  lib/graphql_devise/resource_loader.rb
  lib/graphql_devise/schema_plugin.rb
  spec/dummy/app/controllers/api/v1/graphql_controller.rb
  spec/dummy/app/graphql/dummy_schema.rb
  spec/dummy/app/graphql/interpreter_schema.rb
  spec/dummy/app/graphql/types/mutation_type.rb
  spec/dummy/app/graphql/types/query_type.rb
  spec/dummy/config/routes.rb
  spec/generators/graphql_devise/install_generator_spec.rb
  spec/requests/user_controller_spec.rb
  spec/services/mount_method/operation_preparer_spec.rb
  spec/services/mount_method/operation_preparers/custom_operation_preparer_spec.rb
  spec/services/mount_method/operation_preparers/default_operation_preparer_spec.rb
  spec/services/mount_method/operation_preparers/resource_name_setter_spec.rb
  spec/services/resource_loader_spec.rb
  spec/services/schema_plugin_spec.rb
Labels: bug, enhancement

#100 Avoid returning user information on password reset mutation
  config/locales/en.yml
  lib/graphql_devise/default_operations/mutations.rb
  lib/graphql_devise/default_operations/resolvers.rb
  lib/graphql_devise/mount_method/operation_preparers/default_operation_preparer.rb
  lib/graphql_devise/mount_method/operation_preparers/gql_name_setter.rb
  lib/graphql_devise/mount_method/operation_preparers/mutation_field_setter.rb
  lib/graphql_devise/mount_method/operation_preparers/resolver_type_setter.rb
  lib/graphql_devise/mount_method/operation_preparers/resource_name_setter.rb
  lib/graphql_devise/mutations/resend_confirmation.rb
  lib/graphql_devise/mutations/send_password_reset.rb
  spec/requests/mutations/resend_confirmation_spec.rb
  spec/requests/mutations/send_password_reset_spec.rb
  spec/services/mount_method/operation_preparer_spec.rb
  spec/services/mount_method/operation_preparers/default_operation_preparer_spec.rb
  spec/services/mount_method/operation_preparers/mutation_field_setter_spec.rb
Labels: Security

#107 Fix set_resource_by_token no mapping error in no eager load envs
  README.md
  app/controllers/graphql_devise/concerns/set_user_by_token.rb
  lib/graphql_devise/schema_plugin.rb
  spec/dummy/app/controllers/api/v1/graphql_controller.rb
  spec/dummy/config/routes.rb
  spec/requests/user_controller_spec.rb
Labels: breaking, bug

#106 Use the url where the schema is mounted in emails links
  app/views/graphql_devise/mailer/confirmation_instructions.html.erb
  app/views/graphql_devise/mailer/reset_password_instructions.html.erb
  lib/graphql_devise/mutations/resend_confirmation.rb
  lib/graphql_devise/mutations/send_password_reset.rb
  lib/graphql_devise/mutations/sign_up.rb
  spec/dummy/app/controllers/api/v1/graphql_controller.rb
  spec/dummy/app/graphql/dummy_schema.rb
  spec/dummy/config/routes.rb
  spec/requests/mutations/resend_confirmation_spec.rb
  spec/requests/mutations/send_password_reset_spec.rb
  spec/requests/queries/confirm_account_spec.rb
Labels: bug

#108 Add support for graphql 1.11
  .travis.yml
  Appraisals
  gemfiles/rails5.2_graphql1.11.gemfile
  gemfiles/rails6.0_graphql1.11.gemfile
  graphql_devise.gemspec
Labels: enhancement

#111 Fix email reconfirmation feature
  README.md
  app/controllers/graphql_devise/concerns/set_user_by_token.rb
  app/models/graphql_devise/concerns/model.rb
  app/views/graphql_devise/mailer/confirmation_instructions.html.erb
  app/views/graphql_devise/mailer/reset_password_instructions.html.erb
  lib/graphql_devise/model/with_email_updater.rb
  lib/graphql_devise/mutations/resend_confirmation.rb
  lib/graphql_devise/mutations/send_password_reset.rb
  lib/graphql_devise/mutations/sign_up.rb
  lib/graphql_devise/resolvers/confirm_account.rb
  spec/dummy/app/graphql/mutations/update_user.rb
  spec/dummy/app/graphql/types/mutation_type.rb
  spec/dummy/config/initializers/devise_token_auth.rb
  spec/dummy/db/migrate/20200621182414_remove_uncofirmed_email_from_admins.rb
  spec/dummy/db/schema.rb
  spec/graphql_devise/model/with_email_updater_spec.rb
  spec/rails_helper.rb
  spec/requests/queries/confirm_account_spec.rb
  spec/requests/user_controller_spec.rb
Labels: breaking, bug
