Repository graphql-devise/graphql_devise, pull requests merged in 2021-06, with the labels that each got.

#186 Add resendConfirmationWithToken mutation
  lib/graphql_devise/default_operations/mutations.rb
  lib/graphql_devise/mutations/resend_confirmation_with_token.rb
  spec/dummy/app/graphql/dummy_schema.rb
  spec/requests/mutations/resend_confirmation_with_token_spec.rb
Labels: enhancement

#187 Deprecate mutations and queries that required a redirect
  lib/graphql_devise/default_operations/mutations.rb
  lib/graphql_devise/default_operations/resolvers.rb
  lib/graphql_devise/mount_method/operation_preparers/default_operation_preparer.rb
  lib/graphql_devise/mount_method/operation_sanitizer.rb
  spec/services/mount_method/operation_sanitizer_spec.rb
Labels: deprecated

#188 Document new registration and confirmation flow
  README.md
  lib/graphql_devise/default_operations/mutations.rb
  lib/graphql_devise/mount_method/operation_sanitizer.rb
Labels: documentation

#190 Improve README
  README.md
Labels: documentation
